# 벡터
* 벡터는 차원이 하나뿐인 배열의 특수한 경우
* 동일한 형식(,,,...)의 정렬된 데이터 목록으로 표시
* [,,,...]

In [6]:
v = [1, 2, 3, 4, 5, 6, 7, 8]
print(v)

[1, 2, 3, 4, 5, 6, 7, 8]

* 벡터의 차원 수와 요소의 유형 확인

In [2]:
typeof(v)

Vector{Int64} (alias for Array{Int64, 1})

* 벡터의 차원 확인

In [3]:
ndims(v)

1

* 벡터 요소의 유형 확인

In [4]:
eltype(v)

Int64

* 벡터의 크기와 길이 확인

In [6]:
size(v)

(8,)

In [7]:
length(v)

8

* 벡터의 요소 접근

In [11]:
println(v[3])
println(v[begin])
print(v[end])

3
1
8

* 여러 요소에 접근

In [5]:
print(v[[2, 3]])

UndefVarError: UndefVarError: `v` not defined

In [15]:
range(1, stop=10, step=2)

1:2:9

In [8]:
v[1:3]

3-element Vector{Int64}:
 1
 2
 3

In [10]:
v[1:2:end]  # start, step, stop

4-element Vector{Int64}:
 1
 3
 5
 7

In [11]:
v[:]  # all elements

8-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8

In [12]:
v = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [13]:
# add one at last
append!(v, 4)

4-element Vector{Int64}:
 1
 2
 3
 4

In [14]:
# add multi
append!(v, [5,6])

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

In [15]:
# add multi
append!(v, 7:8)

8-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8

In [16]:
# add float --> int
append!(v, 3.0)

9-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8
 3

In [17]:
# error
append!(v, 3.1415)

InexactError: InexactError: Int64(3.1415)

In [18]:
isinteger(3.0)

true

In [19]:
v = Float64[1, 2, 3]

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [20]:
append!(v, 3.1415)

4-element Vector{Float64}:
 1.0
 2.0
 3.0
 3.1415

In [21]:
v = [1, 2, 3, 4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [22]:
v[2] = 4  # change value

4

In [23]:
v

4-element Vector{Int64}:
 1
 4
 3
 4

In [24]:
v[3:4] .= 11

2-element view(::Vector{Int64}, 3:4) with eltype Int64:
 11
 11

In [25]:
v

4-element Vector{Int64}:
  1
  4
 11
 11

# 행렬

In [26]:
M = [1 2 3 4; 5 6 7 8]

2×4 Matrix{Int64}:
 1  2  3  4
 5  6  7  8

In [27]:
typeof(M)

Matrix{Int64} (alias for Array{Int64, 2})

In [28]:
eltype(M)

Int64

In [29]:
ndims(M)

2

In [30]:
size(M)

(2, 4)

In [31]:
length(M)

8

In [32]:
M[begin]

1

In [33]:
M[2]

5

In [34]:
M[end - 1]

4

In [35]:
M[1, 2]

2

In [36]:
M[1, [2, 3]]

2-element Vector{Int64}:
 2
 3

In [37]:
M[1:3]

3-element Vector{Int64}:
 1
 5
 2

In [38]:
M[:, 1:3]

2×3 Matrix{Int64}:
 1  2  3
 5  6  7

In [39]:
M[1, :]

4-element Vector{Int64}:
 1
 2
 3
 4

In [40]:
M[:]

8-element Vector{Int64}:
 1
 5
 2
 6
 3
 7
 4
 8

In [42]:
hcat(M, M)  # 수평 연결

2×8 Matrix{Int64}:
 1  2  3  4  1  2  3  4
 5  6  7  8  5  6  7  8

In [43]:
# 수직 연결
vcat(M, M)

4×4 Matrix{Int64}:
 1  2  3  4
 5  6  7  8
 1  2  3  4
 5  6  7  8

In [44]:
cat(M, M; dims=2)  # 행으로

2×8 Matrix{Int64}:
 1  2  3  4  1  2  3  4
 5  6  7  8  5  6  7  8

In [45]:
cat(M, M; dims=1)  # 열로

4×4 Matrix{Int64}:
 1  2  3  4
 5  6  7  8
 1  2  3  4
 5  6  7  8

In [46]:
# 배열 크기가 같아야 함
v= [11, 12]

2-element Vector{Int64}:
 11
 12

In [47]:
hcat(M, v)

2×5 Matrix{Int64}:
 1  2  3  4  11
 5  6  7  8  12

In [48]:
vcat(M, v)

ArgumentError: ArgumentError: number of columns of each array must match (got (4, 1))

# n-차원 배열

In [49]:
[1; 2; 3]

3-element Vector{Int64}:
 1
 2
 3

In [50]:
[1;; 2;; 3]

1×3 Matrix{Int64}:
 1  2  3

In [51]:
[1;;; 2;;; 3]

1×1×3 Array{Int64, 3}:
[:, :, 1] =
 1

[:, :, 2] =
 2

[:, :, 3] =
 3

In [52]:
A = zeros(3, 5, 2)

3×5×2 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [53]:
B = zeros(Int64, 3, 5, 2)

3×5×2 Array{Int64, 3}:
[:, :, 1] =
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

[:, :, 2] =
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

In [54]:
typeof(A)

Array{Float64, 3}

In [55]:
eltype(A)

Float64

In [56]:
ndims(A)

3

In [57]:
size(A)

(3, 5, 2)

In [58]:
length(A)

30

In [61]:
println(B)
B[1]=2
print(B)

[1 0 0 0 0; 0 0 0 0 0; 0 0 0 0 0;;; 0 0 0 0 0; 0 0 0 0 0; 0 0 0 0 0]
[2 0 0 0 0; 0 0 0 0 0; 0 0 0 0 0;;; 0 0

 0 0 0; 0 0 0 0 0; 0 0 0

 0 0]

In [62]:
B[1, 2, 2] = 2
print(B)

[2 0 0 0 0; 0 0 0 0 0; 0 0 0

 0 0;;; 0 2 0 0 0; 0 0 0 0 0; 0 0 0 0 0]

In [63]:
B

3×5×2 Array{Int64, 3}:
[:, :, 1] =
 2  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

[:, :, 2] =
 0  2  0  0  0
 0  0  0  0  0
 0  0  0  0  0

In [64]:
B[2,:,1] .= 4

5-element view(::Array{Int64, 3}, 2, :, 1) with eltype Int64:
 4
 4
 4
 4
 4

In [65]:
B

3×5×2 Array{Int64, 3}:
[:, :, 1] =
 2  0  0  0  0
 4  4  4  4  4
 0  0  0  0  0

[:, :, 2] =
 0  2  0  0  0
 0  0  0  0  0
 0  0  0  0  0

In [66]:
ones(Float32, 2, 3, 1)

2×3×1 Array{Float32, 3}:
[:, :, 1] =
 1.0  1.0  1.0
 1.0  1.0  1.0

In [67]:
fill(1.234, 2, 3, 1)

2×3×1 Array{Float64, 3}:
[:, :, 1] =
 1.234  1.234  1.234
 1.234  1.234  1.234

# Broadcasting

In [68]:
a = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [69]:
a .-= 4

3-element Vector{Int64}:
 -3
 -2
 -1

In [70]:
abs.(a)

3-element Vector{Int64}:
 3
 2
 1

In [71]:
a = [1,2,3]
b = [4,5,6]
a * b

MethodError: MethodError: no method matching *(::Vector{Int64}, ::Vector{Int64})

Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...)
   @ Base operators.jl:578
  *(!Matched::StridedMatrix{T}, ::StridedVector{S}) where {T<:Union{Float32, Float64, ComplexF32, ComplexF64}, S<:Real}
   @ LinearAlgebra C:\Julia-1.9.0\share\julia\stdlib\v1.9\LinearAlgebra\src\matmul.jl:49
  *(::StridedVecOrMat, !Matched::LinearAlgebra.Adjoint{<:Any, <:LinearAlgebra.LQPackedQ})
   @ LinearAlgebra C:\Julia-1.9.0\share\julia\stdlib\v1.9\LinearAlgebra\src\lq.jl:269
  ...


In [72]:
a' * b

32

In [73]:
a * b'

3×3 Matrix{Int64}:
  4   5   6
  8  10  12
 12  15  18

In [74]:
a .* b

3-element Vector{Int64}:
  4
 10
 18

# views

In [75]:
A = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [76]:
B = A

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [77]:
B[2] = 42

42

In [78]:
B

2×3 Matrix{Int64}:
  1  2  3
 42  5  6

In [79]:
A

2×3 Matrix{Int64}:
  1  2  3
 42  5  6

In [80]:
A == B

true

In [81]:
C = copy(A)

2×3 Matrix{Int64}:
  1  2  3
 42  5  6

In [82]:
C[4] = 10

10

In [83]:
A == C

false

In [84]:
D = A[1:2, 1:2]

2×2 Matrix{Int64}:
  1  2
 42  5

In [85]:
D[1] = 15

15

In [86]:
D == A[1:2, 1:2]

false

In [87]:
E = view(A, 1:2, 1:2)

2×2 view(::Matrix{Int64}, 1:2, 1:2) with eltype Int64:
  1  2
 42  5

In [88]:
E = @view A[1:2, 1:2]

2×2 view(::Matrix{Int64}, 1:2, 1:2) with eltype Int64:
  1  2
 42  5

In [89]:
E[4] = 78

78

In [90]:
E == A[1:2, 1:2]

true

In [91]:
E

2×2 view(::Matrix{Int64}, 1:2, 1:2) with eltype Int64:
  1   2
 42  78

In [92]:
typeof(E)

SubArray{Int64, 2, Matrix{Int64}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false}

# Tuple
* 불변의 정렬된 고정 크기 요소
* 추가, 변경이 안됨

In [93]:
t = (1, 2.0, "3")

(1, 2.0, "3")

* (...) 생략 가능

In [94]:
t = 1, 2.0, "3"

(1, 2.0, "3")

In [95]:
typeof(t)

Tuple{Int64, Float64, String}

* 다양한 타입으로 구성 가능

In [96]:
t[1]

1

In [97]:
t[end]

"3"

In [98]:
t[1:2]

(1, 2.0)

In [99]:
a, b, c = t

(1, 2.0, "3")

In [100]:
println("The value stored in the tuple are: $a, $b, and $c")

The value stored in the tuple are: 1, 2.0, and 3


* 변수와 값을 지정하여 만들 수 있음

In [101]:
t = (a = 1, b = 2.0, c = "3")

(a = 1, b = 2.0, c = "3")

In [102]:
a = 1;
b = 2.0;
c = "3";
t = (; a, b, c)

(a = 1, b = 2.0, c = "3")

* 이렇게 만든 tuple은 여러 요소에 동시 접근 불가

In [103]:
t[1]

1

In [104]:
t[end]

"3"

In [105]:
t[1:2]

MethodError: MethodError: no method matching getindex(::NamedTuple{(:a, :b, :c), Tuple{Int64, Float64, String}}, ::UnitRange{Int64})

Closest candidates are:
  getindex(::NamedTuple, !Matched::Int64)
   @ Base namedtuple.jl:136
  getindex(::NamedTuple, !Matched::Symbol)
   @ Base namedtuple.jl:137
  getindex(::NamedTuple, !Matched::Tuple{Vararg{Symbol}})
   @ Base namedtuple.jl:138
  ...


In [106]:
t.a

1

In [107]:
t.c

"3"

In [108]:
a, b, c = t
println("The values stored in the tuple are: a = $a, b = $b, c = $c")

The values stored in the tuple are: a = 1, b = 2.0, c = 3

# Dictionaries
* 키와 값의 쌍으로 구성, 변경 가능, 무작위 순서

In [109]:
d = Dict("a" => [1, 2, 3], "b" => 1)

Dict{String, Any} with 2 entries:
  "b" => 1
  "a" => [1, 2, 3]

* key를 string 대신 symbol로 사용가능

In [111]:
d = Dict(:a => [1, 2, 3], :b => 1)

Dict{Symbol, Any} with 2 entries:
  :a => [1, 2, 3]
  :b => 1

In [112]:
# key를 이용한 dictionary 접근
d[:a]

3-element Vector{Int64}:
 1
 2
 3

In [113]:
# key가 없으면 error
d[:c]

KeyError: KeyError: key :c not found

In [114]:
# key가 있는지 확인
haskey(d, :c)

false

In [115]:
# 확인만 함
get(d, :c, 42)

42

In [116]:
d

Dict{Symbol, Any} with 2 entries:
  :a => [1, 2, 3]
  :b => 1

In [117]:
# 없으면 추가
get!(d, :c, 42)

42

In [118]:
d

Dict{Symbol, Any} with 3 entries:
  :a => [1, 2, 3]
  :b => 1
  :c => 42

In [119]:
get!(d, :d, ["hello", "world"])

2-element Vector{String}:
 "hello"
 "world"

In [120]:
d

Dict{Symbol, Any} with 4 entries:
  :a => [1, 2, 3]
  :b => 1
  :d => ["hello", "world"]
  :c => 42

In [121]:
# key를 이용한 제거
delete!(d, :d)

Dict{Symbol, Any} with 3 entries:
  :a => [1, 2, 3]
  :b => 1
  :c => 42

In [122]:
haskey(d, :d)

false

In [123]:
# 제거 시 값을 반환
pop!(d, :c)

42

In [124]:
haskey(d, :c)

false

In [125]:
# key가 없으면 값만 리턴
pop!(d, :c, 444)

444

In [126]:
haskey(d, :c)

false